[build]
    command = "gatsby build"
    publish = "public"
    functions = "functions"
[dev]
    functions = "functions"
[[redirect]]
    to = "api/*"
    from = ".netlify/functions/:splat"
    status = 200